name: CI Básico Python

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar tests
      env:
        PYTHONPATH: "${{ github.workspace }}/src"
      run: pytest -v

    - name: Ejecutar con cobertura
      env:
        PYTHONPATH: "${{ github.workspace }}/src"
      run: |
        pytest --cov=my_calc_app --cov-report=term --cov-report=html

    - name: Guardar reporte
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
