name: CI Básico Python

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Si prefieres la opción B (instalación editable), descomenta:
        # pip install -e ./src

    - name: Ejecutar tests
      env:
        PYTHONPATH: "${{ github.workspace }}/src"   # quita esta línea si usas opción B
      run: pytest -v

    - name: Ejecutar con cobertura
      env:
        PYTHONPATH: "${{ github.workspace }}/src"   # quita esta línea si usas opción B
      run: |
        pytest --cov=my_calc_app --cov-report=term --cov-report=html

    - name: Guardar reporte
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
